version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pizzaria_db
    environment:
      POSTGRES_USER: pizzaria_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pizzaria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pizzaria-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizzaria_user -d pizzaria"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev
    container_name: pizzaria_api
    ports:
      - "4000:4000"
    depends_on:
       db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://pizzaria_user:1234@db:5432/pizzaria
    restart: unless-stopped
    networks:
      - pizzaria-network
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:

networks:
  pizzaria-network:
    driver: bridge